services:
  app:
    container_name: node-docker
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "30098:30098"
    stdin_open: true
    environment:
      - PORT=30098
      - host=cbn360
      - user=root
      - password=Aku664329#
      - database=seoweb
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Aku664329#
      MYSQL_DATABASE: seoweb
      MYSQL_USER: root
      MYSQL_PASSWORD: Aku664329#
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  node_modules:
  db_data:
