services:
  app:
    container_name: node-docker
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "30098:30098"
    stdin_open: true
    env_file:
      - .env
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container-cbn
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  node_modules:
  db_data:
