services:
  app:
    container_name: node-docker
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "30098:30098"
    stdin_open: true
    environment:
      - PORT=30098
      - host=db
      - user=app_user
      - password=Aku664329#
      - database=seoweb
      - tokensecret=eyJhbGc!
      - APIFY=apify_api_bhrNQzFP0PrgO224texPGqbJM8dcgC0LNsrA
      - admintoken=221100
      - spassword=dULl98s
      - uname=admin_cbn360
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container-cbn
    environment:
      MYSQL_ROOT_PASSWORD: Aku664329#
      MYSQL_DATABASE: seoweb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Aku664329#
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  node_modules:
  db_data:
